[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
# Railway에서 자동으로 설정되는 환경변수들
# PORT는 Railway가 자동으로 설정
# RAILWAY_ENVIRONMENT는 Railway가 자동으로 설정

# 사용자 정의 환경변수 (Railway 대시보드에서 설정)
# MAX_FILE_SIZE_MB = "50"
# MAX_DURATION_SECONDS = "420"
# UPLOAD_DIR = "uploads"
# OUTPUT_DIR = "outputs"