services:
  - type: web
    name: removevocal
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: MAX_FILE_SIZE_MB
        value: 50
      - key: MAX_DURATION_SECONDS
        value: 420
      - key: UPLOAD_DIR
        value: uploads
      - key: OUTPUT_DIR
        value: outputs